name: CI-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: Otus.Teaching.PromoCodeFactory.WebHost

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: dotnet build src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj -c Release -o content

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: content
